# Site settings
title: Charles Harmon
header-img: img/home-bg.jpg
email: chas688@gmail.com
copyright_name: Your/Project/Corporate Name
description: "Musings in the full stack universe."
baseurl: ""
url: "http://chas688.github.io"
twitter_username: HMG_Chas
github_username:  chas688
facebook_username: 
email_username:  chas688@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
